version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: resume-chat-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
      - resume-chat-network

  mongo-express:
    image: mongo-express:latest
    container_name: resume-chat-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - resume-chat-network

networks:
  resume-chat-network:
    driver: bridge

volumes:
  mongodb_data:
